# 서버 설정
server:
  port: 8080 # 애플리케이션 포트 번호

# Spring 프레임워크 설정
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE # JSON 필드 이름을 스네이크 케이스(snake_case)로 변환

# Actuator (관리 및 모니터링) 설정
management:
  endpoints:
    web:
      exposure:
        include: "health,info" # /actuator/health, /actuator/info 엔드포인트 노출
  endpoint:
    health:
      show-details: when_authorized # 인증된 사용자에게만 헬스 체크 상세 정보 노출

# JWT (JSON Web Token) 설정
jwt:
  issuer: board-api # 토큰 발행자
  # prod 환경에서는 반드시 환경 변수로 덮어쓰기
  secret: ${JWT_SECRET:change-me} # JWT 서명 비밀 키
  access-exp-seconds: 900 # 액세스 토큰 유효 시간(초, 15분)
  refresh-exp-seconds: 1209600 # 리프레시 토큰 유효 시간(초, 14일)
